/* ============================================================
 * 小宝CAD 画图训练任务库（供训练循环页与验收器使用）
 * 每个任务：AI 自然语言指令 + 确定性验收标准（几何/结构）
 * 训练闭环：AI 画图 → 验收打分 → MiniMax M3 多模态审阅 → 修复 → 再打分
 * ============================================================ */

export const TRAIN_TASKS = [
  {
    id: 'flange2d',
    ws: '2d',
    name: '法兰盘俯视图（2D）',
    prompt: '请画一个法兰盘俯视图：外圆直径 100（圆心在原点），在半径 35 的圆周上均布 6 个直径 10 的小孔，并画互相垂直的中心线穿过圆心。',
    checks: [
      { type: 'count', kind: 'circle', min: 7, weight: 2 },
      { type: 'circleAt', cx: 0, cy: 0, r: 50, tol: 1, weight: 3 },
      { type: 'holesOnRing', cx: 0, cy: 0, radius: 35, rTol: 1.5, holeR: 5, holeRTol: 1, count: 6, weight: 4 },
      { type: 'linesThrough', cx: 0, cy: 0, min: 2, tol: 3, weight: 2 },
      { type: 'bbox', w: 110, h: 110, tol: 15, weight: 2 },
    ],
  },
  {
    id: 'bracket2d',
    ws: '2d',
    name: '支架轮廓图（2D）',
    prompt: '请画一个支架的外形轮廓：100×60 的矩形外框（左下角在原点），内部在 (20,30) 和 (80,30) 各有一个半径 10 的圆孔。',
    checks: [
      { type: 'count', kind: 'circle', min: 2, weight: 2 },
      { type: 'closedPolylineBbox', w: 100, h: 60, tol: 2, weight: 3 },
      { type: 'circleAt', cx: 20, cy: 30, r: 10, tol: 1, weight: 3 },
      { type: 'circleAt', cx: 80, cy: 30, r: 10, tol: 1, weight: 3 },
    ],
  },
  {
    id: 'plate3d',
    ws: '3d',
    name: '四孔安装板（3D）',
    prompt: '请建一个四孔安装板的三维模型：100×80×10 的长方体板（中心在原点），四个角各打一个半径 8 的通孔（孔心在 (±35,±25)），用差集挖孔。',
    checks: [
      { type: 'featureCount', min: 5, weight: 2 },
      { type: 'kindCount', kind: 'box', min: 1, weight: 2 },
      { type: 'kindCount', kind: 'cylinder', min: 4, weight: 3 },
      { type: 'kindCount', kind: 'boolean', min: 1, weight: 3 },
      { type: 'primDim', kind: 'box', field: 'dx', approx: 100, tol: 3, weight: 2 },
      { type: 'primDim', kind: 'box', field: 'dy', approx: 80, tol: 3, weight: 2 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 8, tol: 1, minCount: 4, weight: 3 },
      { type: 'primPos', kind: 'cylinder', x: 35, y: 25, tol: 2, minCount: 1, weight: 2 },
    ],
  },
  {
    id: 'sleeve3d',
    ws: '3d',
    name: '轴套（3D）',
    prompt: '请建一个轴套的三维模型：外圆柱半径 40、高 60，中心挖一个半径 25 的同心通孔（差集）。',
    checks: [
      { type: 'featureCount', min: 3, weight: 2 },
      { type: 'kindCount', kind: 'cylinder', min: 2, weight: 3 },
      { type: 'kindCount', kind: 'boolean', min: 1, weight: 3 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 40, tol: 2, minCount: 1, weight: 2 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 25, tol: 2, minCount: 1, weight: 2 },
      { type: 'primParam', kind: 'cylinder', field: 'h', approx: 60, tol: 2, minCount: 2, weight: 2 },
    ],
  },

  /* ============ 工业级水泵组件训练（用户核心场景） ============ */
  {
    id: 'impeller3d',
    ws: '3d',
    name: '水泵叶轮（3D）',
    prompt: '请建一个离心泵叶轮：轮盘为半径 60、厚 8 的圆盘（中心在原点），轮毂处挖半径 10 的中心通孔，圆周半径 35 上均布 6 片叶片（每片约 30×6×10），并把叶片与轮盘合并为整体。',
    checks: [
      { type: 'featureCount', min: 9, weight: 2 },
      { type: 'kindCount', kind: 'cylinder', min: 2, weight: 2 },
      { type: 'kindCount', kind: 'box', min: 6, weight: 3 },
      { type: 'kindCount', kind: 'boolean', min: 1, weight: 3 },
      { type: 'primDim', kind: 'cylinder', field: 'r', approx: 60, tol: 2, weight: 2 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 10, tol: 1, minCount: 1, weight: 2 },
      { type: 'ringDist', kind: 'box', cx: 0, cy: 0, radius: 35, tol: 2, minCount: 6, weight: 4 },
      { type: 'angularEven', kind: 'box', cx: 0, cy: 0, radius: 35, tol: 2, maxDevDeg: 5, weight: 3 },
    ],
  },
  {
    id: 'volute2d',
    ws: '2d',
    name: '蜗壳型线（2D）',
    prompt: '请画蜗壳型线剖视图：基圆半径 40（圆心原点）；沿螺旋线每 45° 放置一个切圆（共 8 个），圆心半径从 50 开始每步增加 5（即 50/55/60/65/70/75/80/85，角度 0°~315°）；画竖直中心线穿过原点。',
    checks: [
      { type: 'count', kind: 'circle', min: 9, weight: 2 },
      { type: 'circleAt', cx: 0, cy: 0, r: 40, tol: 1, weight: 3 },
      { type: 'spiralGrowth', cx: 0, cy: 0, minCount: 8, weight: 5 },
      { type: 'linesThrough', cx: 0, cy: 0, min: 1, tol: 2, weight: 2 },
    ],
  },
  {
    id: 'casing3d',
    ws: '3d',
    name: '水泵泵壳（3D）',
    prompt: '请建一个离心泵泵壳（简化蜗壳）：外圆柱半径 70、高 50（中心在原点），底部加 160×100×15 的安装底座，进水口法兰（半径 25、厚 12）在 (0,-90)，出水口法兰（半径 25、厚 12）在 (95,0)，最后用半径 45 的偏心内腔（圆心偏移 x=18）挖出流道。',
    checks: [
      { type: 'featureCount', min: 6, weight: 2 },
      { type: 'kindCount', kind: 'cylinder', min: 4, weight: 2 },
      { type: 'kindCount', kind: 'box', min: 1, weight: 2 },
      { type: 'kindCount', kind: 'boolean', min: 2, weight: 3 },
      { type: 'primDim', kind: 'cylinder', field: 'r', approx: 70, tol: 2, weight: 2 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 45, tol: 2, minCount: 1, weight: 2 },
      { type: 'primPos', kind: 'cylinder', x: 18, y: 0, tol: 2, minCount: 1, weight: 2 },
      { type: 'coaxial', kind: 'cylinder', cx: 0, cy: 0, tol: 2, minCount: 1, weight: 2 },
    ],
  },
  {
    id: 'shaft3d',
    ws: '3d',
    name: '泵轴·台阶轴（3D）',
    prompt: '请建一根五段台阶轴（各段同轴，直径逐段递减）：第 1 段半径 30 长 40，第 2 段半径 25 长 60，第 3 段半径 20 长 80，第 4 段半径 15 长 50，第 5 段半径 10 长 30。',
    checks: [
      { type: 'featureCount', min: 5, weight: 2 },
      { type: 'kindCount', kind: 'cylinder', min: 5, weight: 2 },
      { type: 'coaxial', kind: 'cylinder', cx: 0, cy: 0, tol: 2, minCount: 5, weight: 4 },
      { type: 'primSeq', kind: 'cylinder', field: 'r', dir: 'dec', minCount: 5, weight: 3 },
      { type: 'dimSum', kind: 'cylinder', field: 'h', approx: 260, tol: 5, weight: 3 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 30, tol: 1, minCount: 1, weight: 2 },
    ],
  },
  {
    id: 'pump2d',
    ws: '2d',
    name: '水泵剖视图（2D）',
    prompt: '请画水泵的剖视图：竖直中心线穿过原点；泵壳外轮廓圆半径 70（圆心原点）；内腔圆半径 45（圆心 (18,0)，偏心）；叶轮圆半径 40（圆心原点）；轮毂圆半径 12（圆心原点）。',
    checks: [
      { type: 'count', kind: 'circle', min: 4, weight: 2 },
      { type: 'circleAt', cx: 0, cy: 0, r: 70, tol: 1, weight: 2 },
      { type: 'circleAt', cx: 18, cy: 0, r: 45, tol: 1, weight: 3 },
      { type: 'circleAt', cx: 0, cy: 0, r: 40, tol: 1, weight: 3 },
      { type: 'circleAt', cx: 0, cy: 0, r: 12, tol: 1, weight: 3 },
      { type: 'linesThrough', cx: 0, cy: 0, min: 1, tol: 2, weight: 2 },
    ],
  },
  {
    id: 'minipump3d',
    ws: '3d',
    name: '微型泵整机装配（3D）',
    prompt: '请装配一台微型离心泵：①泵壳：外圆柱半径 70 高 50（原点），偏心内腔半径 45（x=18）用差集挖流道；②叶轮：轮盘半径 60 厚 8，轮毂孔半径 30.5 用差集挖出，6 片叶片（盒体）均布在半径 35 圆周上并与轮盘并集；③泵轴：半径 30 长 120，与叶轮中心孔保持间隙配合（轴 Φ60 / 孔 Φ61）。',
    checks: [
      { type: 'featureCount', min: 12, weight: 2 },
      { type: 'kindCount', kind: 'cylinder', min: 5, weight: 2 },
      { type: 'kindCount', kind: 'box', min: 6, weight: 2 },
      { type: 'kindCount', kind: 'boolean', min: 3, weight: 3 },
      { type: 'primDim', kind: 'cylinder', field: 'r', approx: 70, tol: 2, weight: 2 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 45, tol: 2, minCount: 1, weight: 2 },
      { type: 'ringDist', kind: 'box', cx: 0, cy: 0, radius: 35, tol: 2, minCount: 6, weight: 3 },
      { type: 'coaxial', kind: 'cylinder', cx: 0, cy: 0, tol: 2, minCount: 3, weight: 3 },
      { type: 'fitClearance', outerR: 30, boreR: 30.5, outerTol: 0.4, boreTol: 0.4, minGap: 0.1, maxGap: 1.5, weight: 4 },
    ],
  },
  {
    id: 'pumpdrawing2d',
    ws: '2d',
    name: '水泵总装剖视图·图纸（2D）',
    prompt: '请画水泵总装剖视图（商用图纸）：竖直中心线穿过原点；泵壳外轮廓圆 r70（原点）；内腔圆 r45（圆心 (18,0)）；叶轮圆 r40（原点）；轮毂圆 r12（原点）；并标注关键尺寸：泵壳外径（直径标注 Φ140）、叶轮直径（直径标注 Φ80）、轮毂直径（直径标注 Φ24）、总宽度（线性标注，两端 -90 与 90）。',
    checks: [
      { type: 'count', kind: 'circle', min: 4, weight: 2 },
      { type: 'circleAt', cx: 0, cy: 0, r: 70, tol: 1, weight: 2 },
      { type: 'circleAt', cx: 18, cy: 0, r: 45, tol: 1, weight: 2 },
      { type: 'circleAt', cx: 0, cy: 0, r: 40, tol: 1, weight: 2 },
      { type: 'circleAt', cx: 0, cy: 0, r: 12, tol: 1, weight: 2 },
      { type: 'linesThrough', cx: 0, cy: 0, min: 1, tol: 2, weight: 2 },
      { type: 'dimensionCount', min: 4, weight: 3 },
      { type: 'dimensionCount', subtype: 'diametric', min: 2, weight: 3 },
      { type: 'dimensionCount', subtype: 'linear', min: 1, weight: 2 },
    ],
  },
  {
    id: 'pumpduty3d',
    ws: '3d',
    name: '商用泵·需求驱动设计（3D）',
    prompt: '客户要求一台单级单吸离心泵：流量 Q=100m³/h、扬程 H=32m、转速 n=2900rpm。请先用 pump_sizing 工具计算设计参数，再按参数创建商用级装配模型：泵壳（蜗壳基圆外圆柱 + 偏心内腔差集）、叶轮（轮盘 + 5 片均布叶片 + 轮毂孔差集）、泵轴（与轮毂孔间隙配合）。',
    checks: [
      { type: 'featureCount', min: 12, weight: 2 },
      { type: 'kindCount', kind: 'cylinder', min: 5, weight: 2 },
      { type: 'kindCount', kind: 'box', min: 5, weight: 2 },
      { type: 'kindCount', kind: 'boolean', min: 3, weight: 3 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 98, tol: 2, minCount: 1, weight: 3 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 92.5, tol: 2, minCount: 1, weight: 3 },
      { type: 'ringDist', kind: 'box', cx: 0, cy: 0, radius: 65, tol: 2, minCount: 5, weight: 3 },
      { type: 'angularEven', kind: 'box', cx: 0, cy: 0, radius: 65, tol: 2, maxDevDeg: 6, weight: 2 },
      { type: 'coaxial', kind: 'cylinder', cx: 0, cy: 0, tol: 2, minCount: 3, weight: 3 },
      { type: 'fitClearance', outerR: 15.5, boreR: 16, outerTol: 0.6, boreTol: 0.6, minGap: 0.2, maxGap: 1.5, weight: 4 },
    ],
  },
  {
    id: 'multistage3d',
    ws: '3d',
    name: '两级离心泵（3D）',
    prompt: '请建一台两级离心泵：①第一级泵壳段：外圆柱半径 70 高 50（z=0），偏心内腔半径 45（x=18）差集挖流道；②第二级泵壳段：同样的外圆柱与内腔放在 z=50；③每级一个叶轮：轮盘半径 60 厚 8、中心孔半径 30.5 差集、6 片叶片（盒体）均布半径 35 并集；④一根长轴半径 30 长 200 贯穿两级；⑤两端各一个轴承座：内径面半径 32 高 20（z=-20 与 z=200）。轴、叶轮孔、轴承孔必须同轴且间隙逐级为正。',
    checks: [
      { type: 'featureCount', min: 25, weight: 2 },
      { type: 'kindCount', kind: 'cylinder', min: 11, weight: 2 },
      { type: 'kindCount', kind: 'box', min: 12, weight: 2 },
      { type: 'kindCount', kind: 'boolean', min: 6, weight: 3 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 70, tol: 2, minCount: 2, weight: 3 },
      { type: 'primParam', kind: 'cylinder', field: 'r', approx: 60, tol: 2, minCount: 2, weight: 2 },
      { type: 'ringDist', kind: 'box', cx: 0, cy: 0, radius: 35, tol: 2, minCount: 12, weight: 3 },
      { type: 'coaxial', kind: 'cylinder', cx: 0, cy: 0, tol: 2, minCount: 6, weight: 3 },
      { type: 'fitChain', cx: 0, cy: 0, axisTol: 2, weight: 4, chain: [
        { name: '轴', r: 30, tol: 0.4 },
        { name: '叶轮孔', r: 30.5, tol: 0.4 },
        { name: '轴承孔', r: 32, tol: 0.5 },
      ] },
    ],
  },
];

export const taskById = (id) => TRAIN_TASKS.find((t) => t.id === id) || null;
